zackchase/mxnet-the-straight-dope

- convert.sh
- remove_output.py
run `bash convert.sh` will convert notebooks into markdown files, which can be merged into mxnet directly
> add converter

- P01-C02-ndarray.ipynb
Hello,
Trivial typo fix here in the ndarray ipynb.
Thanks,
Chris
> trivial typo fix

- P02-C04-softmax-regression-gluon.ipynb
- P02-C05-regularization-scratch.ipynb
- P02-C06-regularization-gluon.ipynb
- P14-C03-multiple-gpus-gluon.ipynb
these notebooks are fantastic!
> updating broken links

- P06-C03-object-detection.ipynb
Using L2Loss for now since SmoothL1Loss PR still pending. Working example anyway.
Preview:
[P06-C03-object-detection.pdf](https://github.com/zackchase/mxnet-the-straight-dope/files/1177738/P06-C03-object-detection.pdf)
> add object detection tutorial

- P01-C03-linear-algebra.ipynb
Fix: remove {, add $
Issue: https://github.com/zackchase/mxnet-the-straight-dope/issues/37
> Fix formatting problem in issue #37:

- P01-C01-introduction.ipynb
I've been going through the tutorials and found some typos. Thanks so much for writing them!
First commit: Based on what the following sentence ("Instead, ..."), the preceding sentence should say "we **do not** directly design a system..."
> Fix some typos

- P02-C04-softmax-regression-gluon.ipynb
> Update evaluation section for gluon multiclass LR

- P01-C03-linear-algebra.ipynb
Fixed a typo, and attempted to make description more concise.
> Small tweaks to vector description.

- P02-C01-linear-regression-scratch.ipynb
Would you welcome contributions that primarily fix lint issues (this PR being an example)?  Some issues are pretty minor, so feel free to push back on areas where you prefer your style.
I didn't include it here but 
```python
counter = 0
train_data.reset()
for batch in train_data:
counter += 1
print(counter)
```
can also be written as
```python
print(sum(1 for _ in train_data))
```
I personally find the 'for batch in train_data' most readable.
> Fixed a few linting issues.

- P05-C04-rnns-gluon.ipynb
- P06-C03-object-detection.ipynb
- P14-C05-hybridize.ipynb
> fix params

- P14-C02-multiple-gpus-scratch.ipynb
- P14-C03-multiple-gpus-gluon.ipynb
- P14-C04-training-with-multi-machines.ipynb
- P14-C05-hybridize.ipynb
Correct minor typos, grammatical corrections, and minor code problems.
> minor tweaks

- P01-C03-linear-algebra.ipynb
It was previously saying you can compute the one norm, but showing how to compute the L2-norm.
> Show how to compute the L1-norm

- P04-C02-cnn-gluon.ipynb
- P05-C01-simple-rnn.ipynb
- P05-C02-lstm-scratch.ipynb
- P05-C03-gru-scratch.ipynb
- P05-C04-rnns-gluon.ipynb
- P07-C08-tree-lstm.ipynb
- P10-C01-gan-intro.ipynb
- docs/C01-install.rst
@zackchase  Please feel free to edit the PR as you deem fit before merging it. I have clicked Yes to "Allow edits from maintainers."
The tutorials chosen are the ones mentioned in Alex's ICML PDF file from the "slides" directory.
> fix minor typos

- P02-C04-softmax-regression-gluon.ipynb
Cleanup description on parameter initialization for Multiclass Logistic Regression.
> Cleanup description.

- P03-C05-mlp-batch-norm-scratch.ipynb
https://github.com/zackchase/mxnet-the-straight-dope/issues/151
> Add batchnorm

- P01-C04-probability.ipynb
it seems that \pm fails to be recognized
> Fix jenkins complain

- README.md
- chapter18_variational-methods-and-uncertainty/bayes-by-backprop.ipynb
This notebook implements the _Bayes by Backprop_ algorithm presented by the [Weight Uncertainty in Neural Networks](https://arxiv.org/abs/1505.05424) paper in plain MXNet.
> Add Bayes by Backprop notebook

- chapter02_supervised-learning/linear-regression-scratch.ipynb
Change the text accordingly to the code.
> Text: NDArrayIter -> DataLoader

- chapter03_deep-neural-networks/custom-layer.ipynb
- chapter03_deep-neural-networks/mlp-dropout-gluon.ipynb
- chapter03_deep-neural-networks/mlp-dropout-scratch.ipynb
- chapter03_deep-neural-networks/plumbing.ipynb
- chapter03_deep-neural-networks/serialization.ipynb
Ran through chapter 3 and identified a few issues that are corrected in this PR.
Note that while MD lists in iPython are rendered in increasing order using just "1.", in HTML it is not rendered in increasing order, so you need to manually increment the counter (see my update for plumbing and serialization)
> Doc updates

- chapter01_crashcourse/linear-algebra.ipynb
> linear algebra bug 

- chapter02_supervised-learning/softmax-regression-scratch.ipynb
Fixed some small grammatical and spelling errors.
Note the change in Python version at the end of the commit.  That wasn't intentional.  Hope that isn't too much of a pain.
> Fixed four minor grammatical and spelling errors

- chapter09_natural-language-processing/tree-lstm.ipynb
> Minor typo fix. GPUS to GPUs.

- chapter03_deep-neural-networks/mlp-scratch.ipynb
Resolves https://github.com/zackchase/mxnet-the-straight-dope/issues/259
> Fix use of word 'stochastic'

- chapter03_deep-neural-networks/mlp-dropout-scratch.ipynb
removed as variable is not used in function body
> removed label_one_hot from evaluate_accurcy

- chapter01_crashcourse/introduction.ipynb
Changed the line from "What how wuold we deal with video snippets" to  " But how would we deal with video snippets"
> Typo on line 532 in Introduction

- chapter02_supervised-learning/softmax-regression-gluon.ipynb
old link was http://gluon.mxnet.io/chapter02_supervised-learning/**P02-C03-**softmax-regression-scratch.ipynb, which will return a 404.
> fix broken link

- chapter03_deep-neural-networks/mlp-dropout-scratch.ipynb
Only significant thing is fixing a couple typos and grammatical errors
> Fix a couple of typos and grammatical errors

- cheatsheets/pytorch_gluon.md
Is the initializer section suitable after block definition? @SherlockLiao
cc @szha
> sec 3 `Pytorch module and Gluon blocks`

- chapter01_crashcourse/introduction.ipynb
per issue https://github.com/zackchase/mxnet-the-straight-dope/issues/296
> Added newline character to make list appear

- chapter01_crashcourse/ndarray.ipynb
referencing https://github.com/zackchase/mxnet-the-straight-dope/issues/338
> fix "certian" spelling error

- chapter03_deep-neural-networks/mlp-dropout-gluon.ipynb
Only significant change is the typos.
> Fixed a couple of typos

- chapter01_crashcourse/linear-algebra.ipynb
One typo fix in chapter 1, linear-algebra.ipynb.
> one typo fix: "with with" --> "with"

- chapter02_supervised-learning/logistic-regression-gluon.ipynb
- Fixed an incomplete sentence
- Added a couple equations to explicitly show what p(y|x) looks like, which makes the cross-entropy equation less surprising. The intuition based interpretation remains unchanged.
> Edits on the derivation of binary cross-entropy

- chapter02_supervised-learning/linear-regression-gluon.ipynb
- chapter02_supervised-learning/linear-regression-scratch.ipynb
resaonably -> reasonably
(sorry for making such small contributions - I fix as I go through the tutorial)
> Fix a typo, bullet list, execution output formatting

- cheatsheets/pytorch_gluon.md
Add cheatsheet for data loading and serialization
> add IO serialization

- chapter03_deep-neural-networks/mlp-gluon.ipynb
moved loss.backward() outside of autograd record context; and fixed a typo
> moved loss.backward() outside of autograd record context

- chapter03_deep-neural-networks/plumbing.ipynb
Typos and smoothing out some grammar
> chapter03_deep-neural-networks/plumbing.ipynb

- chapter02_supervised-learning/logistic-regression-gluon.ipynb
Fixed various typos, added a comment clarifying the remapping of labels from {-1,1} to {0,1}, and used asscalar to allow final accuracy numbers to print more prettily.
The reason for the last change is that converting from an NDArray to a numpy float made it print much more nicely.
> Fixed various typos, added a comment, made final results print nicer

- chapter05_recurrent-neural-networks/simple-rnn.ipynb
- sequence in the same row between batches connect to each other (there are probably fancier ways to keep continuity between epochs, it's not implemented here)
- replace number 77 with variable vocab_size
- minor edits in softmax function
- editorial edits: use boldsymbol for vectors
hopefully fixes #378
> corrected sequence chopping plus a few minor things

- cheatsheets/pytorch_gluon.md
finish adding parameters and initialize
> update cheatsheets: pytorch_gluon: parameters and initialize

- chapter03_deep-neural-networks/serialization.ipynb
Made the code flexible for GPU or CPU like all the other notebooks (the previous version would crash on a machine that didn't have a GPU).  Fixed some typos in the text.  Regenerated the output from my machine with the new logic.
> Fix GPU vs CPU logic and fixed some typos

- chapter03_deep-neural-networks/mlp-scratch.ipynb
Some of these are clarifications, so please double-check that you agree with my interpretation.
> Grammars, typos, and some clarifications

- chapter03_deep-neural-networks/custom-layer.ipynb
In addition to the typos and grammar issues, there was an empty cell at the very end which I deleted.  It seemed to have been left there by accident.
> Fixed typos and deleted an unused cell

- chapter02_supervised-learning/logistic-regression-gluon.ipynb
prevent nan outputs in case yhat has exact 0 or 1 elements.
> Replace `sum` with `nansum`

- chapter01_crashcourse/introduction.ipynb
> Fix typo in introduction

- chapter01_crashcourse/introduction.ipynb
Fixed typo in interacting with an environment section
> Fixed typo

- chapter03_deep-neural-networks/mlp-dropout-gluon.ipynb
- chapter03_deep-neural-networks/mlp-gluon.ipynb
- chapter03_deep-neural-networks/mlp-scratch.ipynb
Just a few minor typos in chpt 3 and one sentence to add clarification to the first graphic in the MLP book
> minor typos in chpt 3

- chapter01_crashcourse/probability.ipynb
Adding %matplotlib inline in order to get die probability graph to render in Jupyter
> Add matplotlib inline to make graph render

- chapter04_convolutional-neural-networks/cnn-gluon.ipynb
- chapter04_convolutional-neural-networks/cnn-scratch.ipynb
- chapter04_convolutional-neural-networks/deep-cnns-alexnet.ipynb
Grammatical and minor wording fixes to three files.  Made all default to CPU.  Reset all paragraphs to unexecuted state.
> Grammatical fixes and default to CPU

- chapter03_deep-neural-networks/mlp-gluon.ipynb
I found some very minor spelling errors in chapter 3 mlp-gluon.  I believe this cleans them up. Let me know if this is the right way to make pull requests or if there is some other workflow you prefer : ).
> Fixed minor spelling errors

- chapter05_recurrent-neural-networks/gru-scratch.ipynb
- chapter05_recurrent-neural-networks/lstm-scratch.ipynb
- chapter05_recurrent-neural-networks/simple-rnn.ipynb
I don't know if this is necessary but I noticed that the built in function input was being over written.  I worry that this could lead to some non obvious errors if someone were to copy the code.  What are your thoughts?
> Changed variable input to input_sequence to avoid overloading the built-in function input

- chapter02_supervised-learning/perceptron.ipynb
Fix for the code example:
`ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (1L, 2L) and requested shape (2L,)`
> Fix: ValueError: 

- chapter19_graph-neural-networks/Graph-Neural-Networks.ipynb
As requested by Anima.  @szha, @aaronmarkham asked me to ask you (and him) to review it.  Cheers!
> Adding chapter on Graph Neural Networks

- chapter02_supervised-learning/regularization-gluon.ipynb
At line 189: in plot_learningcurves(), missing plt.show(),  so can't plot the figure.
> Line 189: make plot come true

- chapter02_supervised-learning/logistic-regression-gluon.ipynb
- chapter02_supervised-learning/regularization-scratch.ipynb
- chapter03_deep-neural-networks/mlp-scratch.ipynb
At the line 279 of chapter02 logistic-regression-gluon.ipynb, there is a necessy, and it should be necessary, so I change it.
> spelling correction for chapter02

- chapter03_deep-neural-networks/serialization.ipynb
'makedirs' doesn't accept 'exist_ok' in Python 2. Use 'os.path.exists'
and 'os.makedirs' instead.
> Fix Python 2 incompatibility

- chapter01_crashcourse/introduction.ipynb
Fix typo 'relvant' to 'relevant'.
> Fix typo in introduction.ipynb.

- chapter01_crashcourse/introduction.ipynb
- proto-P02-C02.6-loss.ipynb
crashcourse chapter introduction:
L1 Loss link
L2 Loss link
SoftmaxCELoss
proto-P02-C02.6-loss:
SoftmaxCELoss
> fix broken links

- chapter11_recommender-systems/introduction-to-recommender-systems.ipynb
Adding SVD chapter to recommendation systems
> Adding SVD chapter to recommendation systems

- chapter08_computer-vision/fine-tuning.ipynb
- proto-P02-C02.6-loss.ipynb
tiny typo
link for mxnet.io.ImageRecordIter
> fix typo and broken link for mxnet.io.ImageRecordIter 

- chapter02_supervised-learning/environment.ipynb
- chapter02_supervised-learning/linear-regression-scratch.ipynb
- chapter02_supervised-learning/perceptron.ipynb
This fixes a few typos and removes an unnecessary line of code.
> Small fixes
