P01-C01-introduction.ipynb
Fix the fizzbuzz program to match the specifications of printing both fizz and buzz when the number is divisible by both 3 and 5.
Also, it is advisable to print the result using print() rather than relying on Jupyter notebook's implicit print functionality so that the program can be downloaded and run by the reader and have the exact same behavior as in the Jupyter notebook.
=> Fix fizzbuzz program in P01-C01-introduction.ipynb

chapter07_distributed-learning/multiple-gpus-scratch.ipynb
In the first paragraph of section Automatic Parallelization, there are two "technologies ".
=> fix a grammer error

chapter09_natural-language-processing/tree-lstm.ipynb
Fix a minor typo in Chapter 9 Natural Language Processing. Change informatino to information.
@zackchase
=> Typo fix. informatino to information.

chapter01_crashcourse/introduction.ipynb
The first paragraph of the "Basics of machine learning" section
has an "at" that needs to be removed from the last line. In the gluon site,
the numbering does not render properly even though it does in the Jupyter notebook
UI. I changed 1. 1. 1. 1. to 1. 2. 3. 4.
=> minor grammar and numbering edit in introduction

chapter03_deep-neural-networks/mlp-gluon.ipynb
the gluon helper function for mnist will download the dataset, so you don't need to use the utils function anymore...
=> remove test utils call

chapter02_supervised-learning/perceptron.ipynb, chapter02_supervised-learning/softmax-regression-scratch.ipynb
1.  The truth value of an NDArray is ambiguous. Please convert to number with asscalar() first
location: Perceptron chapter
i = 0
while (i < samples):
tmp = nd.random_normal(shape=(1, dimension))
margin = nd.dot(tmp, wfake) + bfake
if (nd.norm(tmp).asscalar() < 3) & (abs(margin.asscalar()) > epsilon):
X[i, :] = tmp
Y[i] = 1 **if margin > 0 else -1**
i += 1
return X, Y
**change margin to margin.asscalar()**
2.  Check failed: ndinputs[i].ctx().dev_mask() == ctx.dev_mask() (1 vs. 2) All inputs must live on the same context
location: softmax chapter
if we change ctx=mx.cpu() to ctx=mx.gpu(id). we will encounter this error. That is because not all inputs are on gpu. 
To fix it, we should allocate W and b on gpu too:
W = nd.random_normal(shape=(num_inputs, num_outputs),**ctx=ctx**)
b = …
=> fix errors in perception and softmax

cheatsheets/pytorch_gluon.md
Pytorch also has a context manager `torch.cuda.device(dev_id)` as described in http://pytorch.org/docs/master/notes/cuda.html.
Add section 1.4 `cross device`.
cc @szha
=> Add context scope for pytorch and 1.4 `cross device` and 2 `autograd`

chapter07_distributed-learning/multiple-gpus-gluon.ipynb, chapter07_distributed-learning/multiple-gpus-scratch.ipynb
Currently there is a mismatch in the n/w used for "Training on multiple GPUs from scratch" and for "Training on multiple GPUs with gluon". We should try to use the same pooling everywhere. Since lenet uses max-pooling using that as the standard here.
Second issue is that learning rate is made a multiple of gpus. Under certain cases that makes sense but under this case, it reduces the accuracy significantly which I don't think is a good idea for tutorials for beginners as it throws them off. For instance w/ max-pooling, gluon tutorial resulted in an accuray of around 11% on gpus (learning rate = 0.6) whereas on 1 gpu it was about 98% (learning = 0.3)
=> For lenet cnn use max-pooling. learning-rate independent of gpus.

cheatsheets/pytorch_gluon.md
A list of ops that are different in PyTorch and Gluon. Did not document ops that are the same.
=> Add torch.Tensor ops to PyTorch cheetsheet

chapter03_deep-neural-networks/mlp-dropout-gluon.ipynb
Some coders may be more familiar with pkeep, so it is best to add explanation of which way the % works. An alternative would be to change the code and have the % different for each layer and explain it in the code.
=> added explanation of the sense of dropout parameter

chapter03_deep-neural-networks/mlp-scratch.ipynb
The existing qualitative description is already pretty long, I think we should just make it clear how log_softmax works.
Actually the description is slightly inaccurate. The worry about large numbers is the reason we do the subtraction of max in softmax (this hasn't been explained in other tutorials I think). The log softmax is mainly to deal with underflow (i.e. avoid exact zero softmax probably output).
=> Explaining log_softmax

cheatsheets/pytorch_gluon.md
Add two sections of `Pytorch optimizer vs Gluon Trainer` and `Monitoring` in pytorch_gluon cheatsheet.
Please notice that the subsection of `zero_grad for grad_req is 'add'` is removed, because I think this is not commonly used in training. Feel free to ask me to add this subsection back if you think it is neccessary.
cc @szha
=> [pytorch_gluon cheatsheet] Add sections `Pytorch optimizer vs Gluon Trainer` and `Monitoring`

chapter08_computer-vision/fine-tuning.ipynb
I tried running this on a P3 with 4 GPUs and hit errors there at the end. Was able to bypass the first wave by adding context, and verified this still works with CPU only. 
Would be happy to add additional fixes, but I'm not sure how to fix it, so maybe just go with this first pass and circle back.
This was the issue I partially resolved but just pushed it down a bit...
It would fail here:
```
deep_dog_net.load_params('deep-dog-5a342a6f.params', mx.cpu())
```
But changing `mx.cpu()` to `contexts` gets it past that block.
Then it fails on:
```
classify_hotdog(deep_dog_net, '../img/real_hotdog.jpg')
...
RuntimeError: Parameter deep_dog_conv0_weight was not initialized on context cpu(0). It was only initialized on [gpu(0), gpu(1), gpu(2), gpu(3)].
```
classify_hotdog doesn't take a context …
=> fixed some typos; added context fix for multi-gpu

chapter14_generative-adversarial-networks/gan-intro.ipynb
Expression for calculating covariance was correctly documented as $A^\\top A$, but the code and output were incorrect.
=> gan-intro: minor fixes

chapter18_variational-methods-and-uncertainty/bayes-by-backprop-gluon.ipynb
Fixes two minor typos in Chapter 18:
1. 2 mispellings of 'network'
2. a mispelling of 'special'
=> fix typos in text

chapter02_supervised-learning/regularization-scratch.ipynb
The word "overparametrized" of 310 line should be "overparameterized".
=> Spelling Correction of 310 line

chapter07_distributed-learning/hybridize.ipynb
The previous way of exporting an hybridized model as advertised in Chapter7 does not work anymore in 1.2.0 impacting users who relied on this technique to save their models @piiswrong is working on a fix to keep supporting the old behavior. 
In the meanwhile there is a new cleaner API for exporting a hybridized model using `.export()`, which replace the old advertised way and I have updated the notebook accordingly.
In the works is also `SymbolBlock.imports()` that will let you import directly the exported model back to Gluon, ETA end of this week. 
Please refer to: https://github.com/apache/incubator-mxnet/pull/11127
@piiswrong @zackchase @srochel @szha 
New wording:
=> Update chapter 7 save API

chapter13_unsupervised-learning/vae-gluon.ipynb
Adding arguments needed to call `super()` in Python 2.
=> Fix example to work with Python 2

chapter12_time-series/intro-forecasting-2-gluon.ipynb
I have changed the data source to an automatically downloadable one - Sea level rise: https://datahub.io/core/sea-level-rise (public license - ODC-PDDL-1.0) I take only last 50 rows, so the chart would look better once plotted.
I also found a small bug (shape mismatch) and fixed it.
Please, let me know if you are fine with this datasource. If not, please, send me a link to the one to use. 
Thank you.
=> Bug fix and data source change

chapter12_time-series/issm-scratch.ipynb
Seaborn package is not used in this notebook, but it is not installed by default on CI machine. Removing it from source.
=> Removing unused seaborn package

chapter01_crashcourse/autograd.ipynb
MXNet integration tests of the Straight Dope (contained here:
http://jenkins.mxnet-ci.amazon-ml.com/job/NightlyTests_onBinaries/)
execute the notebook and line-scan for warnings and errors in the
output.
Kindly requesting we change 'Warning:' to 'Caution:' to avoid triggering
the log scan regular expression that normally picks up otherwise, we'll
require parsing the JSON in a more heavyweight manner.
=> Minor word change to avoid triggering warnings.

chapter02_supervised-learning/regularization-gluon.ipynb, chapter12_time-series/issm-scratch.ipynb
Fixing some notebooks that contained invalid JSON. These notebooks are
causing the test pipline at ci.mxnet.io to fail at present
(http://ci.mxnet.io/job/mxnet-the-straight-dope/88/console) and will
cause the Nightly test on Binaries at
http://jenkins.mxnet-ci.amazon-ml.com/job/NightlyTests_onBinaries/ to
fail if we enable them.
=> Fixing invalid JSON in two notebooks.

build/build.sh
Starting with conda v4.4, `source activate` is discouraged. The CI server now runs conda 4.5 so the Jenkinsfile needs to be adapted.
=> Update Jenkinsfile for CI server conda upgrade

chapter03_deep-neural-networks/custom-layer.ipynb, chapter03_deep-neural-networks/mlp-dropout-gluon.ipynb, chapter03_deep-neural-networks/mlp-dropout-scratch.ipynb, chapter03_deep-neural-networks/mlp-gluon.ipynb, chapter03_deep-neural-networks/mlp-scratch.ipynb, chapter03_deep-neural-networks/plumbing.ipynb, chapter03_deep-neural-networks/serialization.ipynb
- Use GPU if one exists
- Use `save_parameters` instead of `save_params` and `load_parameters` instead of `load_params`
- Move the code that needs at least 2 GPUs to run under `if len(mx.test_utils.list_gpus()) >= 2:`
- Create NDArray in the chosen content instead of always cerating in CPU. Example:
`dense.collect_params().initialize(ctx=ctx)`
=> Some changes for testing these notebooks on CI

chapter05_recurrent-neural-networks/rnns-gluon.ipynb
The rnn gluon notebook takes much too long on the CPU. It takes ~ 5 minutes on a p3.8xl using one of the GPUs.
=> Chapter 5's rnn-gluon notebook to use GPU.

build/build.sh
This change lists packages installed in Conda to assist in debugging an issue with Sphinx that is preventing html from being generated. See 
http://ci.mxnet.io/blue/organizations/jenkins/mxnet-the-straight-dope/detail/mxnet-the-straight-dope/103/pipeline
=> List conda packages installed for easier debugging

build/build.sh
The current conda environment is stuck on old versions and those old
versions are failing the build. Recreating Conda environment to allow
for latest versions to be chosen.
=> Create new conda environment to get latest packages.

build/index.rst
#69 
More detailed instructions Link is broken in the [Dependencies Section](http://gluon.mxnet.io/#dependencies)
Broken Link : `http://gluon.mxnet.io/docs/C01-install.html`
Pointing the link to [Mxnet's Installation Guide](http://mxnet.incubator.apache.org/install/index.html)
=> Changed the Broken link from docs/C01-install.html to mxnet.io's installation guide
